import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme';
import { CssBaseline } from "@mui/material";
import SideBar from "./Components/SideBar/SideBar";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) 
{
  return (
    <html lang="en" suppressHydrationWarning>
       <body className={roboto.variable}>
          <AppRouterCacheProvider>
            <InitColorSchemeScript attribute="class" />
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <SideBar>
                {children}
              </SideBar>
            </ThemeProvider>
          </AppRouterCacheProvider>
       </body>
     </html>
  );
}
